// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content_links.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createContentLink = `-- name: CreateContentLink :one
INSERT INTO content_links(id, platform, title, description, url, thumbnail_url, published_at, created_at, updated_at) 
VALUES (
  gen_random_UUID(),
  $1, -- platform
  $2, -- title
  $3, -- description
  $4, -- url
  $5, -- thumbnail_url
  $6, -- published_at
  NOW(), -- created_at
  NOW() -- updated_at
  ) 
  returning id, platform, title, description, url, thumbnail_url, published_at, created_at, updated_at
`

type CreateContentLinkParams struct {
	Platform     string
	Title        string
	Description  sql.NullString
	Url          string
	ThumbnailUrl sql.NullString
	PublishedAt  sql.NullTime
}

type CreateContentLinkRow struct {
	ID           uuid.UUID
	Platform     string
	Title        string
	Description  sql.NullString
	Url          string
	ThumbnailUrl sql.NullString
	PublishedAt  sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

func (q *Queries) CreateContentLink(ctx context.Context, arg CreateContentLinkParams) (CreateContentLinkRow, error) {
	row := q.db.QueryRowContext(ctx, createContentLink,
		arg.Platform,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.ThumbnailUrl,
		arg.PublishedAt,
	)
	var i CreateContentLinkRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.ThumbnailUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContentLinkById = `-- name: DeleteContentLinkById :exec
DELETE FROM content_links WHERE id = $1
`

func (q *Queries) DeleteContentLinkById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteContentLinkById, id)
	return err
}

const getContentLinkById = `-- name: GetContentLinkById :one
SELECT id, platform, title, description, url, thumbnail_url, published_at, created_at, updated_at from content_links where id = $1
`

type GetContentLinkByIdRow struct {
	ID           uuid.UUID
	Platform     string
	Title        string
	Description  sql.NullString
	Url          string
	ThumbnailUrl sql.NullString
	PublishedAt  sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

func (q *Queries) GetContentLinkById(ctx context.Context, id uuid.UUID) (GetContentLinkByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getContentLinkById, id)
	var i GetContentLinkByIdRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.ThumbnailUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentLinks = `-- name: GetContentLinks :many
SELECT id, platform, title, description, url, thumbnail_url, published_at, created_at, updated_at from content_links
`

type GetContentLinksRow struct {
	ID           uuid.UUID
	Platform     string
	Title        string
	Description  sql.NullString
	Url          string
	ThumbnailUrl sql.NullString
	PublishedAt  sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

func (q *Queries) GetContentLinks(ctx context.Context) ([]GetContentLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, getContentLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContentLinksRow
	for rows.Next() {
		var i GetContentLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.ThumbnailUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
