// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events(id, type, poster_path, is_featured, created_at, updated_at, start_date, end_date, description, title, location_name, location_city, location_maps_link)
VALUES (
  gen_random_UUID(),
  $1, -- type
  $2, -- poster_path
  $3, -- is_featured
  NOW(), -- created_at
  NOW(), -- updated_at
  $4, -- start_date
  $5, -- end_date
  $6, -- description
  $7, -- title
  $8, -- location_name
  $9, -- location_city
  $10 -- location_maps_link
  )
returning  id, type, poster_path, is_featured, created_at, updated_at, start_date, end_date, description, title, location_name, location_city, location_maps_link, active
`

type CreateEventParams struct {
	Type             string
	PosterPath       sql.NullString
	IsFeatured       bool
	StartDate        time.Time
	EndDate          sql.NullTime
	Description      string
	Title            string
	LocationName     sql.NullString
	LocationCity     sql.NullString
	LocationMapsLink sql.NullString
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Type,
		arg.PosterPath,
		arg.IsFeatured,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
		arg.Title,
		arg.LocationName,
		arg.LocationCity,
		arg.LocationMapsLink,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.PosterPath,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
		&i.Title,
		&i.LocationName,
		&i.LocationCity,
		&i.LocationMapsLink,
		&i.Active,
	)
	return i, err
}

const getActiveEvents = `-- name: GetActiveEvents :many
SELECT id, type, poster_path, is_featured, created_at, updated_at, start_date, end_date, description, title, location_name, location_city, location_maps_link, active from events where active = true
`

func (q *Queries) GetActiveEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getActiveEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.PosterPath,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartDate,
			&i.EndDate,
			&i.Description,
			&i.Title,
			&i.LocationName,
			&i.LocationCity,
			&i.LocationMapsLink,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEvents = `-- name: GetAllEvents :many
SELECT id, type, poster_path, is_featured, created_at, updated_at, start_date, end_date, description, title, location_name, location_city, location_maps_link, active from events
`

func (q *Queries) GetAllEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.PosterPath,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartDate,
			&i.EndDate,
			&i.Description,
			&i.Title,
			&i.LocationName,
			&i.LocationCity,
			&i.LocationMapsLink,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventById = `-- name: GetEventById :one
SELECT id, type, poster_path, is_featured, created_at, updated_at, start_date, end_date, description, title, location_name, location_city, location_maps_link, active from events where id = $1
`

func (q *Queries) GetEventById(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.PosterPath,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
		&i.Title,
		&i.LocationName,
		&i.LocationCity,
		&i.LocationMapsLink,
		&i.Active,
	)
	return i, err
}
