// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Product struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Active      bool
	Description string
	Name        string
	Category    string
	Price       int32
	Stock       int32
}

type ProductImage struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Path      string
	IsPrimary bool
}

type User struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	EmailVerifiedAt sql.NullTime
	Password        string
	DeactivatedAt   sql.NullTime
}
