// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ContentLink struct {
	ID           uuid.UUID
	Platform     string
	Title        string
	Description  sql.NullString
	Url          string
	ThumbnailUrl sql.NullString
	PublishedAt  sql.NullTime
	IsFeatured   sql.NullBool
	SortOrder    sql.NullInt32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Event struct {
	ID               uuid.UUID
	Type             string
	PosterPath       sql.NullString
	IsFeatured       sql.NullBool
	CreatedAt        time.Time
	UpdatedAt        time.Time
	StartDate        time.Time
	EndDate          sql.NullTime
	Description      sql.NullString
	Title            string
	LocationName     sql.NullString
	LocationCity     sql.NullString
	LocationMapsLink sql.NullString
}

type Product struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Active      bool
	Description string
	Name        string
	Category    string
	Price       int32
	Stock       int32
}

type ProductImage struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Path      string
	IsPrimary bool
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	EmailVerifiedAt sql.NullTime
	Password        string
	DeactivatedAt   sql.NullTime
	Role            string
}
