// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_images.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProductImage = `-- name: CreateProductImage :one
insert into product_images(id, product_id, created_at, updated_at, path, is_primary)
values (
  gen_random_UUID(),
  $1,
  NOW(),
  NOW(),
  $2,
  $3
  )
  returning id, product_id, created_at, updated_at, path, is_primary
`

type CreateProductImageParams struct {
	ProductID uuid.UUID
	Path      string
	IsPrimary bool
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, createProductImage, arg.ProductID, arg.Path, arg.IsPrimary)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Path,
		&i.IsPrimary,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
delete from product_images where id = $1
`

func (q *Queries) DeleteProductImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductImage, id)
	return err
}

const getProductImageByImageId = `-- name: GetProductImageByImageId :one
select id, product_id, created_at, updated_at, path, is_primary from product_images where id = $1
`

func (q *Queries) GetProductImageByImageId(ctx context.Context, id uuid.UUID) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, getProductImageByImageId, id)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Path,
		&i.IsPrimary,
	)
	return i, err
}

const getProductImagesByProductId = `-- name: GetProductImagesByProductId :many
select id, product_id, created_at, updated_at, path, is_primary from product_images where product_id = $1
`

func (q *Queries) GetProductImagesByProductId(ctx context.Context, productID uuid.UUID) ([]ProductImage, error) {
	rows, err := q.db.QueryContext(ctx, getProductImagesByProductId, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Path,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
