// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
insert into products(id, created_at, updated_at, active, description, name, category, stock, price)
values (
  gen_random_UUID(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
  )
  returning id, created_at, updated_at, active, description, name, category, stock, price
`

type CreateProductParams struct {
	Active      bool
	Description string
	Name        string
	Category    string
	Stock       int32
	Price       int32
}

type CreateProductRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Active      bool
	Description string
	Name        string
	Category    string
	Stock       int32
	Price       int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Active,
		arg.Description,
		arg.Name,
		arg.Category,
		arg.Stock,
		arg.Price,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.Description,
		&i.Name,
		&i.Category,
		&i.Stock,
		&i.Price,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
delete from products where id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getActiveProducts = `-- name: GetActiveProducts :many
select id, created_at, updated_at, active, description, name, category, price, stock from products where active = true
`

func (q *Queries) GetActiveProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
			&i.Description,
			&i.Name,
			&i.Category,
			&i.Price,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProducts = `-- name: GetAllProducts :many
select id, created_at, updated_at, active, description, name, category, price, stock from products
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
			&i.Description,
			&i.Name,
			&i.Category,
			&i.Price,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductById = `-- name: GetProductById :one
select id, created_at, updated_at, active, description, name, category, price, stock from products where id = $1
`

func (q *Queries) GetProductById(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.Description,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.Stock,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
update products set updated_at = NOW(), name = $2, description = $3, category = $4, stock = $5, price = $6, active = $7 where id = $1 
  returning id, created_at, updated_at, active, description, name, category, stock, price
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Category    string
	Stock       int32
	Price       int32
	Active      bool
}

type UpdateProductRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Active      bool
	Description string
	Name        string
	Category    string
	Stock       int32
	Price       int32
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Stock,
		arg.Price,
		arg.Active,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.Description,
		&i.Name,
		&i.Category,
		&i.Stock,
		&i.Price,
	)
	return i, err
}
