// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, expires_at, revoked_at, user_id, created_at from refresh_tokens where id = $1
`

type GetRefreshTokenRow struct {
	ID        uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserID    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) GetRefreshToken(ctx context.Context, id uuid.UUID) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, id)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const makeRefreshToken = `-- name: MakeRefreshToken :one
INSERT INTO refresh_tokens(id, user_id, created_at, expires_at) 
  values (
gen_random_UUID(),
  $1,
  NOW(),
  $2
  )
  returning id, expires_at
`

type MakeRefreshTokenParams struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type MakeRefreshTokenRow struct {
	ID        uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) MakeRefreshToken(ctx context.Context, arg MakeRefreshTokenParams) (MakeRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, makeRefreshToken, arg.UserID, arg.ExpiresAt)
	var i MakeRefreshTokenRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, id)
	return err
}
