// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into users(id, created_at, updated_at, email, email_verified_at, password, deactivated_at, role)
values(
  gen_random_UUID(),
  NOW(),
  NOW(),
  $1,
  NULL,
  $2,
  NULL,
  $3
  )
  returning id, created_at, updated_at, email, email_verified_at, deactivated_at, role
`

type CreateUserParams struct {
	Email    string
	Password string
	Role     string
}

type CreateUserRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	EmailVerifiedAt sql.NullTime
	DeactivatedAt   sql.NullTime
	Role            string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Password, arg.Role)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DeactivatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, created_at, updated_at, email, email_verified_at, deactivated_at, role from users where email = $1
`

type GetUserByEmailRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	EmailVerifiedAt sql.NullTime
	DeactivatedAt   sql.NullTime
	Role            string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DeactivatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByEmailForAuth = `-- name: GetUserByEmailForAuth :one
select id, created_at, updated_at, email, email_verified_at, deactivated_at, role, password from users where email = $1
`

type GetUserByEmailForAuthRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	EmailVerifiedAt sql.NullTime
	DeactivatedAt   sql.NullTime
	Role            string
	Password        string
}

func (q *Queries) GetUserByEmailForAuth(ctx context.Context, email string) (GetUserByEmailForAuthRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailForAuth, email)
	var i GetUserByEmailForAuthRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DeactivatedAt,
		&i.Role,
		&i.Password,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
select id, created_at, updated_at, email, email_verified_at, deactivated_at, role from users where id = $1
`

type GetUserByIdRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	EmailVerifiedAt sql.NullTime
	DeactivatedAt   sql.NullTime
	Role            string
}

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DeactivatedAt,
		&i.Role,
	)
	return i, err
}
