// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into users(id, created_at, updated_at, email, email_verified_at, password, deactivated_at)
values(
  gen_random_UUID(),
  NOW(),
  NOW(),
  $1,
  NULL,
  $2,
  NULL
  )
  returning id, created_at, updated_at, email, email_verified_at, deactivated_at
`

type CreateUserParams struct {
	Email    string
	Password string
}

type CreateUserRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	EmailVerifiedAt sql.NullTime
	DeactivatedAt   sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Password)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DeactivatedAt,
	)
	return i, err
}
